name: Windows 2025 WSL2 Networking Issue Reproduction

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2025
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: wsl --install -d Ubuntu-24.04 --name reproduction --no-launch
      - name: Allow firewall rule
        shell: powershell
        run: |
          $wslAdapter = Get-NetAdapter | Where-Object {$_.Name -like "*WSL*"}
          if ($wslAdapter) {
              $wslIP = Get-NetIPAddress -InterfaceIndex $wslAdapter.InterfaceIndex | Where-Object {$_.AddressFamily -eq "IPv4"}
              if ($wslIP) {
                  $networkRange = "$($wslIP.IPAddress)/$($wslIP.PrefixLength)"
                  Write-Host "Found WSL network: $networkRange"
                  netsh advfirewall firewall add rule name="WSL2-Auto" dir=in action=allow protocol=TCP remoteip=$networkRange
              }
          }
      - run: node repro.mjs
